### ISSUE TITLE
Stopped working in Firefox Nightly

### ISSUE THREAD

**Issue by meyerweb** [jbalogh/bookmark-shortcut-keys#2]
In the last couple of days, the extension stopped working in Nightly 25.0a1.  It didn’t fail silently; the compatibility check fails and the extension is automatically disabled by Firefox, and it says so.  Unfortunately, I don’t know any more than that.

**Comment by jbalogh** [comment]
Damn you firefox.

**Comment by jbalogh** [comment]
I don't know when the new version will show up as an update, but you can download it directly from here: https://addons.mozilla.org/firefox/downloads/file/221322/bookmark_shortcut_keys-0.75-fx.xpi

**Comment by meyerweb** [comment]
Works like a charm.  Thank you!  You rock.
